color: blue
fieldLayouts:
  b5f39594-4dfb-477b-a358-ea2dac368b7b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 39703860-5ae6-48ba-aa12-902df66c55b0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9a8fffce-3c28-4326-8f7a-e31d2f6cc04b # Builder: Content - Section - Section Background Color
            handle: null
            includeInCards: true
            instructions: null
            label: 'Section Background Color'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 483ce826-3abf-48ac-8c95-5114bda99f30
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 74b87138-1475-47c2-a9dd-63baa78dd5f5 # Builder: Content - Section - Space Between Blocks
            handle: null
            includeInCards: false
            instructions: null
            label: 'Space Between Blocks'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 16c62a98-e675-40ee-a4d0-8ca2543ed5de
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: aa7883a4-2cce-4316-85f3-ec6ea59402ec # Builder: Content - Section - Section Padding Vertical
            handle: null
            includeInCards: false
            instructions: null
            label: 'Section Padding Vertical'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d2acb96f-9f12-4449-ad76-d024ad3d28ab
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 5cb029e3-a009-451e-8ab8-a2a2dec9a3f5
        userCondition: null
handle: blockSection
hasTitleField: false
icon: puzzle-piece
name: Section
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
