color: orange
fieldLayouts:
  1abefa28-ba0b-4e7e-be2b-12835562bb01:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0cf2cfcd-8309-40c2-a08e-fecc444cc2a7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 023e5cc9-a8b0-4377-ab34-aa6bbae891ce # Builder: Content - Video - Video Provider
            handle: null
            includeInCards: true
            instructions: null
            label: 'Video Provider'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 56ba41cc-81fb-441c-ab80-4e153a009184
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: e9486b85-fd5e-40c8-851b-a6b0133e1f88 # Builder: Content - Video - Video Id
            handle: null
            includeInCards: false
            instructions: null
            label: 'Video Id'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 209e0b27-694f-492c-8618-f97820ac8a2a
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 3ac3bfdf-e50b-46e3-abb9-cef4bffab4a0 # Builder: Content - Video - Autoplay
            handle: null
            includeInCards: false
            instructions: null
            label: Autoplay
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 85e4faf3-8c53-4926-9624-5ba7b9cca49b
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 4a25e574-679a-4d01-8e8b-d5927129ce33 # Builder: Content - Video - Loop
            handle: null
            includeInCards: false
            instructions: null
            label: Loop
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca8a500e-d6df-4d29-b957-9e9f7172facc
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 68109da0-245f-4b21-b040-b7f4385e618e # Builder: Content - Video - Video Width
            handle: null
            includeInCards: false
            instructions: null
            label: 'Video Width'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6b9c294a-c00e-4b45-b0e5-c0ff793155ac
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: bb2df4f8-8532-459f-ae5f-12b9013d58c0
        userCondition: null
handle: blockVideo
hasTitleField: false
icon: play
name: Video
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
