color: blue
fieldLayouts:
  a4335b2d-af34-4544-b20a-e4a928a3693c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7f4a2670-3dbf-4d2e-be39-8895186f18d8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1b37c439-5a32-4e8f-8019-7f6a94593419 # Builder: Content - Spacer - Spacer Variant
            handle: null
            includeInCards: true
            instructions: null
            label: 'Spacer Variant'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c8ba7044-fa9a-4546-9493-16bccb73a76e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1ce6448e-436d-4f3c-b18e-d4b338f00b99
        userCondition: null
handle: blockSpacer
hasTitleField: false
icon: up-right-and-down-left-from-center
name: Spacer
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
