color: fuchsia
fieldLayouts:
  7b6ace88-ae82-4caf-afe4-1650ce6e7ce3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ffc1bd43-a44e-424a-b203-665a1e08453b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0a7dd988-f4db-40b7-8112-6f6fc7c4fb54 # Builder: Content - Text : Image - Text
            handle: text
            includeInCards: true
            instructions: null
            label: Text
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 51b01a52-b32f-4ffa-910d-ef9fe863f1ef
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b81cb731-dd6f-4055-9c6d-2f076a727a27 # Builder: Content - Text : Image - Image
            handle: null
            includeInCards: false
            instructions: null
            label: Image
            providesThumbs: true
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ab6dd79a-0d9c-4799-860a-01a7c242ba68
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 98f7a455-6764-4b7d-8d19-405bdcc42228 # Builder: Content - Text : Image - Image Transform
            handle: null
            includeInCards: false
            instructions: null
            label: 'Image Transform'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 04337482-6861-47b4-8a21-cd4447d746ab
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 6a90dae3-938c-47e6-8e36-6b1d6be92d63 # Builder: Content - Text : Image - Show Image Caption
            handle: showImageCaption
            includeInCards: false
            instructions: null
            label: 'Show Image Caption'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 50f248bd-1435-4f9e-8225-ce71ceadbd90
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 210de09a-f6c8-42dd-b4d6-c1c00e7d0b82 # Builder: Content - Text : Image - Image Position
            handle: null
            includeInCards: false
            instructions: null
            label: 'Image Position'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1ce2335a-ddf7-4a2f-a788-0c629ecec74b
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: a7ac4d85-057b-421c-a16b-b382da491a30
        userCondition: null
handle: blockTextImage
hasTitleField: false
icon: shapes
name: 'Text : Image'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
