color: orange
fieldLayouts:
  6c449cd7-ebc2-4ce6-be61-1e8c90cb176b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d6075865-d3fd-4c11-a91d-2f4585505210
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 04773ec9-2a7e-4a5f-a6b0-400be1407e10 # Builder: Content - Images - Variant
            handle: null
            includeInCards: true
            instructions: null
            label: Variant
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4eb72c29-0754-4af1-a1ad-cf28df5c8431
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 75195ab8-b7c4-4dca-b807-ef8a042ef5a9 # Builder: Content - Images - Images
            handle: null
            includeInCards: false
            instructions: null
            label: Images
            providesThumbs: true
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d10b279e-4bce-49cf-90fd-0a2fae06d537
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 62883121-63a2-4e5c-a6f3-4855cf64df2c # Builder: Content - Images - Image Ratio
            handle: null
            includeInCards: false
            instructions: null
            label: 'Image Ratio'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 721a9d99-a7c1-4462-b772-b18fadab09e8
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: e0e9e510-46ff-45aa-aa46-700b325bb911 # Builder: Content - Images - Show Image Caption
            handle: null
            includeInCards: false
            instructions: null
            label: 'Show Image Caption'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9eae0590-a0dc-4c71-8d19-af63a55af1bd
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 56042e3e-7a7b-4a4c-9222-63e004682c9b
        userCondition: null
handle: blockImages
hasTitleField: false
icon: images
name: Images
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
