fieldLayouts:
  d9e47404-d530-49be-957f-79a2ee567d15:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0024100c-6131-4b31-a1cd-50ee6822faee
            warning: null
            width: 100
          -
            fieldUid: 55a8f195-17f6-41b9-983f-06bb0d4b973e # Entry: Custom Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 36c1de9f-aa1e-4b73-8309-b9d5a3089f95
            warning: null
            width: 100
          -
            fieldUid: 45510f13-91d2-479f-9ff2-68dd09ab6643 # Entry: Short Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ba38993b-650f-4cad-bb0e-0f7997b75f78
            warning: null
            width: 100
          -
            fieldUid: 0dc851b0-a289-4c50-be8d-0c055b270ee8 # Entry: Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 24cac873-2dcb-4442-8f4e-35145299398c
            warning: null
            width: 100
        name: Entry
        uid: 8ccd4ebc-87b4-4708-9e42-be5f4a588429
      -
        elements:
          -
            fieldUid: 74eb36ae-7a26-4e7d-b454-990ec52617f0 # Builder: Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 35aeceb5-c17c-4f03-885d-98ae21012fbe
            warning: null
            width: 100
        name: Content
        uid: 5052bf85-c159-48ca-8026-63ffdc7fea05
      -
        elements:
          -
            fieldUid: d29e8520-ab62-4c8f-bda2-61868797c1ca # Entry: SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: de3b8d47-3711-4e69-a7d6-d9828792176f
            warning: null
            width: 100
        name: SEO
        uid: 1f04ebd9-d50b-4ebb-b0a1-3e175abc5c8b
handle: contentBuilder
hasTitleField: true
name: 'Content Builder'
section: 3547e7b4-f3fb-4cf4-9d29-9f12dfa94594 # News
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
