fieldLayouts:
  4f9f544b-c770-4705-b052-b4a4512c58bd:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b497fa68-9dd4-48bd-83cc-3410ddc51086
            warning: null
            width: 100
          -
            fieldUid: 55a8f195-17f6-41b9-983f-06bb0d4b973e # Entry: Custom Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 19971e89-f258-41cb-94e1-de0767176d75
            warning: null
            width: 100
          -
            fieldUid: 45510f13-91d2-479f-9ff2-68dd09ab6643 # Entry: Short Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4464c485-2ddc-4509-af72-0da60a5b48a2
            warning: null
            width: 100
          -
            fieldUid: 0dc851b0-a289-4c50-be8d-0c055b270ee8 # Entry: Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bd8093f9-a064-4f9d-b0a7-92f2c11f9917
            warning: null
            width: 100
        name: Entry
        uid: 6ccb9fc2-a43e-4198-8ac2-775b84e5daa7
      -
        elements:
          -
            fieldUid: 74eb36ae-7a26-4e7d-b454-990ec52617f0 # Builder: Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fbd64c43-4088-48c3-96a3-e2a9d56d5a8b
            warning: null
            width: 100
        name: Content
        uid: bca6d5c3-5af2-4e5f-8952-5614555469eb
      -
        elements:
          -
            fieldUid: d29e8520-ab62-4c8f-bda2-61868797c1ca # Entry: SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e0b0eeb6-3a6c-4441-9298-99660e6f329e
            warning: null
            width: 100
        name: SEO
        uid: c955cd25-d7c1-4287-a3b1-ba9aec3e0841
handle: contentBuilder
hasTitleField: true
name: 'Content Builder'
section: b0207f48-be48-49ab-a759-1ff51f232df3 # Pages
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
