fieldLayouts:
  61f3d7e8-4728-49c4-bb2c-8e26fdff4b77:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 534106d6-e983-4ff3-9290-85f43c36e877
            warning: null
            width: 100
          -
            fieldUid: 55a8f195-17f6-41b9-983f-06bb0d4b973e # Entry: Custom Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 33623269-d54f-4be2-834f-63a79a85fc4b
            warning: null
            width: 100
          -
            fieldUid: 45510f13-91d2-479f-9ff2-68dd09ab6643 # Entry: Short Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: db927374-0d82-49c5-8192-6896430a5a68
            warning: null
            width: 100
          -
            fieldUid: 0dc851b0-a289-4c50-be8d-0c055b270ee8 # Entry: Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 133d098f-83d3-4997-b4ba-9d6cfe395432
            warning: null
            width: 100
        name: Entry
        uid: 5466ab01-f12e-4088-a106-e6c2ce21676f
      -
        elements:
          -
            fieldUid: d29e8520-ab62-4c8f-bda2-61868797c1ca # Entry: SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3054f87c-e594-4196-8166-7f7f2b3b7633
            warning: null
            width: 100
        name: SEO
        uid: 3edcce5a-c1c4-43cc-aeca-62382f35261b
handle: error
hasTitleField: true
name: Error
section: e5172a18-ed16-4229-89ca-fc0dc776597a # Error Pages
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
