fieldLayouts:
  39b9e1a8-a9fe-46a4-aad9-966389ae8743:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: dd63bc42-f4e0-4ecd-a5c7-288a5e7946b2
            warning: null
            width: 100
          -
            fieldUid: 55a8f195-17f6-41b9-983f-06bb0d4b973e # Entry: Custom Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f5f75a83-68e5-4f42-8414-b17906934031
            warning: null
            width: 100
          -
            fieldUid: 45510f13-91d2-479f-9ff2-68dd09ab6643 # Entry: Short Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e249e650-b151-4cd9-aabb-a505665947c5
            warning: null
            width: 100
          -
            fieldUid: 0dc851b0-a289-4c50-be8d-0c055b270ee8 # Entry: Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fd27b23d-962d-4454-a2ad-8d680b53033c
            warning: null
            width: 100
        name: Content
        uid: 19f2f3ee-8dd2-4cb7-a283-067d9468d7a5
      -
        elements:
          -
            fieldUid: d29e8520-ab62-4c8f-bda2-61868797c1ca # Entry: SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ee0f87a2-09fe-40be-ae32-32d65f24fb3f
            warning: null
            width: 100
        name: SEO
        uid: 19225308-28cc-46b1-8075-f4dc542c6c81
handle: overviewNews
hasTitleField: true
name: 'Overview News'
section: b0207f48-be48-49ab-a759-1ff51f232df3 # Pages
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
