import React from "react";
import {graphqlClient} from "../lib/graphql/client/graphql-client";
import {QueryEntriesAllDocument, MetaEntryFragment} from "../lib/graphql/gql/graphql";
import Link from "next/link";

/* Webfonts */
import { JetBrains_Mono, Merriweather_Sans, Merriweather } from '@next/font/google';

const fontJetBrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-mono',
  weight: 'variable'
});
const fontMerriweatherSans = Merriweather_Sans({
  subsets: ['latin'],
  variable: '--font-sans',
  weight: 'variable'
});
const fontMerriweather = Merriweather({
  subsets: ['latin'],
  variable: '--font-serif',
  style: ['italic', 'normal'],
  weight: '900'
});

/* CSS Imports */
import '../css/app.css';

const getEntriesAll = async (section: string[]) => {
  return await graphqlClient.request(QueryEntriesAllDocument, {
    section
  })
}


const RootLayout = async ({children}: { children: React.ReactNode }) => {
  const {entries} = await getEntriesAll(['pages', 'home', 'news'])

  return (
    <html lang="en" className={`${fontMerriweather.variable} ${fontMerriweatherSans.variable} ${fontJetBrainsMono.variable}`}>
    <head>
      <title>{entries.find((entry: MetaEntryFragment) => entry.slug === '__home__')?.title}</title>
      <meta
        property="og:image"
        content="https://nextjs.baukasten.dev/api/og"
      />
      <meta name="description" content="Generated by create next app"/>
      <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1,viewport-fit=cover"/>
      <link rel="icon" href="/favicon.ico"/>
    </head>
    <body>

    <div className={'h-full flex flex-col md:flex-row'}>
      <aside className={'w-72 shrink-0 bg-gray-100 py-20 px-6'}>
        <h2 className={'text-2xl font-mono'}>Navigation</h2>
        <ul className={'flex flex-col gap-4'}>
          {entries && entries.map((entry: MetaEntryFragment) => {
            if (entry?.uri && entry?.title)
              return (
                <>
                  <li>
                    <Link className={'border-b block py-2 text-xs  hover:border-gray-400 transition-all'}
                          href={entry.uri === '__home__' ? '' : entry.uri}>{entry.title}</Link>
                  </li>
                </>
              )
          })}
        </ul>
      </aside>
      <main className={'flex-1 p-20'}>
        {children}
      </main>
    </div>
    </body>
    </html>
  )
}

export default RootLayout
