import React from "react";
import {graphqlClient} from "../lib/graphql/client/graphql-client";
import {QueryEntriesAllDocument, QueryNavigationDocument} from "../lib/graphql/gql/graphql";
import Link from "next/link";
import { Header } from "../components/Header/Header";
import { Footer } from "../components/Footer/Footer";
import { Container } from "../components/Container/Container";

/* Webfonts */
import { JetBrains_Mono, Merriweather_Sans, Merriweather } from '@next/font/google';

const fontJetBrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-mono',
  weight: 'variable'
});
const fontMerriweatherSans = Merriweather_Sans({
  subsets: ['latin'],
  variable: '--font-sans',
  weight: 'variable'
});
const fontMerriweather = Merriweather({
  subsets: ['latin'],
  variable: '--font-serif',
  style: ['italic', 'normal'],
  weight: '900'
});

/* CSS Imports */
import '../css/app.css';

const getNavigation = async (navHandle: string) => {
  return await graphqlClient.request(QueryNavigationDocument, {
    navHandle
  })
}


const RootLayout = async ({children}: { children: React.ReactNode }) => {
  const {navigation} = await getNavigation('navigationMain')

  return (
    <html lang="en" className={`${fontMerriweather.variable} ${fontMerriweatherSans.variable} ${fontJetBrainsMono.variable}`}>
    <head>
      <meta name="description" content="Generated by create next app"/>
      <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1,viewport-fit=cover"/>
      <link rel="icon" href="/favicon.ico"/>
      <title></title>
    </head>
    <body>
    <Header navItems={JSON.stringify(navigation)} />
    <Container tag={'main'} className={'py-20'}>
      {children}
    </Container>
    <Footer />
    </body>
    </html>
  )
}

export default RootLayout
