import {graphqlClient} from "../lib/graphql/client/graphql-client";
import {queryEntriesAll} from "../lib/graphql/queries/entries.all.graphql";
import Link from "next/link";

export const revalidate = false
const getEntriesAll = async (section: string[]) => {
  return await graphqlClient.request(queryEntriesAll, {
    section
  })
}


const RootLayout = async ({children}: { children: React.ReactNode }) => {
  const { entries } = await getEntriesAll(['pages', 'home', 'news'])

  return (
    <html lang="en">
    <head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app"/>
      <link rel="icon" href="/favicon.ico"/>
    </head>
    <body>
    <aside>
      <h2>Aside</h2>
      <ul>
        {entries && entries.map((entry) => {
          if (entry?.uri && entry?.title)
            return (
              <>
                <li>
                  <Link href={entry.uri === '__home__' ? '' : entry.uri}>{entry.title}</Link>
                </li>
              </>
            )
        })}
      </ul>
    </aside>
    <main>
      {children}
    </main>
    </body>
    </html>
  )
}

export default RootLayout
