field: 74eb36ae-7a26-4e7d-b454-990ec52617f0 # Builder: Content
fieldLayouts:
  aa114924-5aa2-41f4-85a8-bca9eeb2183f:
    tabs:
      -
        elements:
          -
            fieldUid: 1509cbec-547c-4338-bcc8-a5452ab8c801 # Images
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dd770e69-a4d3-4edd-b3b0-d9bfbaec7c64
            warning: null
            width: 100
        name: Content
        uid: 90ce938f-350d-4cc9-8381-c8a86abb1448
fields:
  1509cbec-547c-4338-bcc8-a5452ab8c801: # Images
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: null
    name: Images
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:f1b38495-8096-48fa-9b78-0da345e3295c' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:6c5fc0dd-cf56-48d8-8af8-88abe763b970' # Files
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: true
      showUnpermittedVolumes: true
      source: null
      sources:
        - 'volume:f1b38495-8096-48fa-9b78-0da345e3295c' # Images
      targetSiteId: null
      validateRelatedElements: true
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: blockImageGallery
name: 'Image Gallery'
sortOrder: 8
