field: 74eb36ae-7a26-4e7d-b454-990ec52617f0 # Builder: Content
fieldLayouts:
  e22d570c-156e-4591-a91a-2af67c7ed22b:
    tabs:
      -
        elements:
          -
            fieldUid: 53f0660a-f06b-4b2d-b342-1869c5c65538 # Quote
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bd2dc568-fec5-4384-b6d0-dc26b5dd7b34
            warning: null
            width: 100
          -
            fieldUid: c40b8b5e-0ccb-4d0d-9eee-bd24ac9209b0 # Source
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9fcea238-ad3d-4958-9762-4a3f7c2cb1e9
            warning: null
            width: 50
          -
            fieldUid: 75b6f580-613f-42ae-aa23-2d5fb22ff3da # Source Subline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 81e0a6bb-2f47-4d2f-b800-a0a2651a916f
            warning: null
            width: 50
          -
            fieldUid: e11e03f7-19c1-45c3-935e-1994a7ce7d26 # Source Url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 25bfda37-86b0-4276-ae59-e34d406c5eba
            warning: null
            width: 50
        name: Content
        uid: 8e061a5e-d78f-48e7-b026-09c9f9a49a67
fields:
  53f0660a-f06b-4b2d-b342-1869c5c65538: # Quote
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: quote
    instructions: null
    name: Quote
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  75b6f580-613f-42ae-aa23-2d5fb22ff3da: # Source Subline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: sourceSubline
    instructions: null
    name: 'Source Subline'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c40b8b5e-0ccb-4d0d-9eee-bd24ac9209b0: # Source
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: source
    instructions: null
    name: Source
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e11e03f7-19c1-45c3-935e-1994a7ce7d26: # Source Url
    columnSuffix: null
    contentColumnType: string(255)
    fieldGroup: null
    handle: sourceUrl
    instructions: null
    name: 'Source Url'
    searchable: false
    settings:
      maxLength: 255
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
handle: blockQuote
name: Quote
sortOrder: 4
