columnSuffix: twbwiyps
contentColumnType: text
fieldGroup: d383bdc6-fcfa-4652-9155-d7ead2d89f29 # Assets
handle: assetTitle
instructions: null
name: 'Asset: Title'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
