columnSuffix: null
contentColumnType: string
fieldGroup: 8512e79b-4bb8-4d2d-b731-5fa98546f2c9 # Builders
handle: builderContent
instructions: null
name: 'Builder: Content'
searchable: true
settings:
  contentTable: '{{%matrixcontent_buildercontent}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
