columnSuffix: null
handle: imagePosition
instructions: null
name: 'Builder: Content - Text : Image - Image Position'
searchable: false
settings:
  default: false
  offLabel: Left
  onLabel: Right
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
