columnSuffix: null
handle: loop
instructions: null
name: 'Builder: Content - Video - Loop'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
