columnSuffix: ibratpfs
contentColumnType: text
fieldGroup: 9bd92523-0b29-45e6-bbe4-d1fcc325091b # SEO
handle: seoSEOmatic
instructions: null
name: 'SEO: SEOmatic'
searchable: false
settings:
  elementDisplayPreviewType: google
  facebookEnabledFields: ''
  facebookTabEnabled: ''
  generalEnabledFields:
    - seoPreview
    - mainEntityOfPage
    - seoTitle
    - seoDescription
    - seoKeywords
    - seoImage
    - robots
    - canonicalUrl
  generalTabEnabled: '1'
  sitemapEnabledFields: ''
  sitemapTabEnabled: ''
  twitterEnabledFields: ''
  twitterTabEnabled: ''
translationKeyFormat: null
translationMethod: none
type: nystudio107\seomatic\fields\SeoSettings
