columnSuffix: null
handle: showImageCaption2
instructions: null
name: 'Builder: Content - Text : Image - Show Image Caption'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
