columnSuffix: null
handle: snippet
instructions: null
name: 'Builder: Content - Code - Snippet'
searchable: false
settings:
  availableLanguages:
    - css
    - graphql
    - html
    - javascript
    - json
    - markdown
    - mysql
    - php
    - shell
    - twig
    - typescript
    - yaml
  codeFolding: true
  defaultValue: ''
  fontSize: 14
  language: javascript
  lineNumbers: true
  monacoEditorOptions: ''
  placeholder: ''
  showLanguageDropdown: true
  singleLineEditor: false
  theme: vs-dark
translationKeyFormat: null
translationMethod: none
type: nystudio107\codefield\fields\Code
