columnSuffix: null
handle: snippetCollapsed
instructions: null
name: 'Builder: Content - Code - Snippet collapsed'
searchable: false
settings:
  default: false
  offLabel: 'False'
  onLabel: 'True'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
