columnSuffix: ktdckrbv
contentColumnType: string(255)
fieldGroup: 0a568f7c-6f94-4167-b21f-a50a4292ea1d # Text
handle: textSourceUrl
instructions: null
name: 'Text: Source Url'
searchable: true
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: site
type: craft\fields\Url
