columnSuffix: ktdckrbv
contentColumnType: string(255)
handle: textSourceUrl
instructions: null
name: 'Text: Source Url'
searchable: true
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: site
type: craft\fields\Url
