columnSuffix: null
handle: text
instructions: null
name: 'Builder: Content - Text - Text'
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: 9576c20c-3c74-4f97-a5a6-683f176df53e # Rich Text Default
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: true
  wordLimit: null
translationKeyFormat: null
translationMethod: site
type: craft\ckeditor\Field
