columnSuffix: null
handle: videoWidth
instructions: null
name: 'Builder: Content - Video - Video Width'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Wide
        -
          - value
          - wide
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Narrow
        -
          - value
          - narrow
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
