fieldLayouts:
  2ffc1297-6481-42bf-8cba-e3bc0fde84c2:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: a638da57-27af-4485-ae76-ba87b3eeea1f
            warning: null
            width: 100
          -
            fieldUid: 1516a801-6243-468d-b8e2-479085458faa # Asset: Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b4d2577f-6732-42fd-ac37-ac7b1c8dd18a
            warning: null
            width: 100
          -
            fieldUid: aac37142-e533-49aa-8665-b8cc6360e98b # Asset: Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 97b047e1-8f88-4f78-94bb-7473324b0235
            warning: null
            width: 100
        name: Content
        uid: 03e36f1a-9425-43d4-9fea-59f3f9190e6e
fs: files
handle: files
name: Files
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
