defaultPlacement: end
enableVersioning: false
entryTypes:
  - 8ced5be5-13b2-483f-8db9-aab9757aad21 # Error
handle: errorPages
name: 'Error Pages'
propagationMethod: all
siteSettings:
  8153a2df-373f-4aac-9a92-d52292c9f1aa: # Baukasten (en)
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: '{slug}'
  b205e203-99d0-4ee4-b75c-90a868606c4b: # Baukasten (de)
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: '{slug}'
type: channel
