defaultPlacement: end
enableVersioning: true
handle: home
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
  -
    __assoc__:
      -
        - label
        - 'NuxtJS Localhost'
      -
        - urlFormat
        - 'http://localhost:3000/{uri}?preview=true'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  8153a2df-373f-4aac-9a92-d52292c9f1aa: # $SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: __home__
type: single
