#import "./fragments/entry/fragment.entry.metaData.graphql"
#import "./fragments/asset/fragment.asset.metaData.graphql"
#import "./fragments/asset/fragment.entry.dates.graphql"
#import "./fragments/asset/fragment.asset.imager.auto.graphql"
#import "./fragments/asset/fragment.asset.focalpoint.graphql"

query entriesPages(
  $section: [String] = "pages",
  $queryEntryImage: Boolean = true,
  $formatTimezone: String = "Europe/Berlin",
  $formatLocale: String = "de",
) {
  entriesPages: entries(section: $section) {
    ...entryMetaData
    ...entryDates
    ... on pages_contentBuilder_Entry {
      entryImage(limit: 1) @include(if: $queryEntryImage) {
        ...assetMetaData
        ...assetImagerAuto
        ...assetFocalpoint
      }
    }
  }
}


