data:
  availability: always
  availabilityFrom: null
  availabilitySubmissions: null
  availabilityTo: null
  dataRetention: forever
  dataRetentionValue: null
  fileUploadsAction: retain
  notifications:
    -
      attachFiles: true
      bcc: null
      cc: null
      conditions: null
      content: '[{"type":"paragraph","content":[{"type":"text","text":"A user submission has been made on the \""},{"type":"variableTag","attrs":{"label":"Form Name","value":"{formName}"}},{"type":"text","text":"\" form on "},{"type":"variableTag","attrs":{"label":"Site Name","value":"{siteName}"}},{"type":"text","text":" at "},{"type":"variableTag","attrs":{"label":"Timestamp (yyyy-mm-dd hh:mm:ss)","value":"{timestamp}"}}]},{"type":"paragraph","content":[{"type":"text","text":"Their submission details are:"}]},{"type":"paragraph","content":[{"type":"variableTag","attrs":{"label":"All Form Fields","value":"{allFields}"}}]}]'
      enableConditions: false
      enabled: true
      formId: null
      from: null
      fromName: null
      id: stencil618e487f01f51
      name: 'Admin Notification'
      replyTo: '{field.emailAddress}'
      replyToName: null
      subject: 'A new submission was made on "{formName}"'
      templateId: null
      to: '{systemEmail}'
      uid: null
    -
      attachFiles: true
      bcc: null
      cc: null
      conditions: null
      content: '[{"type":"paragraph","content":[{"type":"text","text":"Thanks again for contacting us. Our team will get back to you as soon as we can."}]},{"type":"paragraph","content":[{"type":"text","text":"As a reminder, you submitted the following details at "},{"type":"variableTag","attrs":{"label":"Timestamp (yyyy-mm-dd hh:mm:ss)","value":"{timestamp}"}}]},{"type":"paragraph","content":[{"type":"variableTag","attrs":{"label":"All Form Fields","value":"{allFields}"}}]}]'
      enableConditions: false
      enabled: true
      formId: null
      from: null
      fromName: null
      id: stencil618e487f01f53
      name: 'User Notification'
      replyTo: null
      replyToName: null
      subject: 'Thanks for contacting us!'
      templateId: null
      to: '{field.emailAddress}'
      uid: null
  pages:
    -
      id: new1272610411
      label: 'Page 1'
      rows:
        -
          fields:
            -
              brandNewField: false
              columnWidth: 12
              handle: yourName
              hasLabel: true
              id: new7715-7348
              label: 'Your Name'
              settings:
                conditions: '{"showRule":"show","conditionRule":"all","conditions":[]}'
                enableConditions: false
                firstNameCollapsed: false
                firstNameDefaultValue: ''
                firstNameEnabled: true
                firstNameLabel: 'First Name'
                firstNamePlaceholder: 'e.g. Peter'
                firstNameRequired: true
                handle: yourName
                instructions: 'Please enter your full name.'
                instructionsPosition: verbb\formie\positions\FieldsetStart
                label: 'Your Name'
                labelPosition: ''
                lastNameCollapsed: false
                lastNameDefaultValue: ''
                lastNameEnabled: true
                lastNameLabel: 'Last Name'
                lastNamePlaceholder: 'e.g. Sherman'
                lastNameRequired: true
                limitType: characters
                middleNameCollapsed: true
                middleNameDefaultValue: ''
                middleNameEnabled: false
                middleNameLabel: 'Middle Name'
                placeholder: 'Your name'
                prefixCollapsed: true
                prefixDefaultValue: ''
                prefixEnabled: false
                prefixLabel: Prefix
                required: true
                subfieldLabelPosition: ''
                useMultipleFields: false
                visibility: ''
              type: verbb\formie\fields\formfields\Name
              vid: new7959-8511
          id: new8990-9934
        -
          fields:
            -
              brandNewField: false
              columnWidth: 12
              handle: emailAddress
              hasLabel: true
              id: new6482-9528
              label: 'Email Address'
              settings:
                conditions: '{"showRule":"show","conditionRule":"all","conditions":[]}'
                handle: emailAddress
                instructions: 'Please enter your email so we can get in touch.'
                instructionsPosition: ''
                label: 'Email Address'
                labelPosition: ''
                limitType: characters
                placeholder: 'e.g. psherman@wallaby.com'
                required: true
                validateDomain: false
                visibility: ''
              type: verbb\formie\fields\formfields\Email
              vid: new7965-6031
          id: new9524-8509
        -
          fields:
            -
              brandNewField: false
              columnWidth: 12
              handle: message
              hasLabel: true
              id: new982-7322
              label: Message
              settings:
                conditions: '{"showRule":"show","conditionRule":"all","conditions":[]}'
                handle: message
                instructions: 'Please enter your comments.'
                instructionsPosition: ''
                label: Message
                labelPosition: ''
                limit: true
                limitAmount: '5000'
                limitType: characters
                placeholder: 'e.g. The reason for my enquiry is...'
                required: true
                visibility: ''
              type: verbb\formie\fields\formfields\MultiLineText
              vid: new8144-535
          id: new2177-9685
      settings:
        backButtonLabel: Back
        buttonsPosition: left
        label: 'Page 1'
        showBackButton: false
        submitButtonLabel: 'Contact us'
      sortOrder: 0
  requireUser: false
  settings:
    availabilityMessage: null
    availabilityMessageDate: null
    availabilityMessageSubmissions: null
    collectIp: false
    collectUser: false
    dataRetention: null
    dataRetentionValue: null
    defaultEmailTemplateId: null
    defaultInstructionsPosition: verbb\formie\positions\AboveInput
    defaultLabelPosition: verbb\formie\positions\AboveInput
    disableCaptchas: false
    displayCurrentPageTitle: false
    displayFormTitle: false
    displayPageProgress: false
    displayPageTabs: false
    errorMessage: '[{"type":"paragraph","content":[{"type":"text","text":"Couldn’t save submission due to errors."}]}]'
    errorMessagePosition: top-form
    fileUploadsAction: null
    integrations:
      duplicate:
        enabled: '1'
        showAllPages: '1'
      honeypot:
        enabled: '1'
        showAllPages: '1'
      javascript:
        enabled: '1'
        showAllPages: '1'
    loadingIndicator: spinner
    loadingIndicatorText: null
    progressPosition: end
    redirectUrl: null
    scrollToTop: true
    storeData: false
    submissionTitleFormat: '{timestamp}: {field.yourName} <{field.emailAddress}>'
    submitAction: message
    submitActionFormHide: true
    submitActionMessage: '[{"type":"paragraph","content":[{"type":"text","text":"Thank you for contacting us! Our team will get in touch shortly to follow up on your message."}]}]'
    submitActionMessagePosition: top-form
    submitActionMessageTimeout: null
    submitActionTab: null
    submitActionUrl: null
    submitMethod: ajax
    userDeletedAction: null
    validationOnFocus: true
    validationOnSubmit: true
  userDeletedAction: retain
defaultStatus: 7e8fd607-0b56-4196-9e02-76ebba9ad7bd # New
handle: contact
name: Contact
submitActionEntry: null
template: null
