fieldLayouts:
  2ffc1297-6481-42bf-8cba-e3bc0fde84c2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: a638da57-27af-4485-ae76-ba87b3eeea1f
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 55a8f195-17f6-41b9-983f-06bb0d4b973e # Text: Title Overwrite
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c940efd1-6f32-429c-9afd-4b517b021aef
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: aac37142-e533-49aa-8665-b8cc6360e98b # Text: Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 97b047e1-8f88-4f78-94bb-7473324b0235
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 03e36f1a-9425-43d4-9fea-59f3f9190e6e
        userCondition: null
fs: files
handle: files
name: Files
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
