fieldLayouts:
  0a4045e3-76db-4cd4-8347-e2eab25d0bd1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 08838209-78ab-4068-a8e0-044ff96432ee
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 55a8f195-17f6-41b9-983f-06bb0d4b973e # Text: Title Overwrite
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 13f1286e-66a1-4d0d-81e8-318dd1095370
            userCondition: null
            warning: null
            width: 50
          -
            attribute: alt
            class: null
            cols: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 87fce2b9-c8a7-40b9-9e77-00456e07a9fd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: aac37142-e533-49aa-8665-b8cc6360e98b # Text: Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dc9d4562-974b-4af0-b234-d24d1162cdfa
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 86a0304b-60f0-4f7a-9b45-de3c05eec04b # Text: Source
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5bcce5eb-6170-47e1-b985-6bd74eba86a7
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: bc1e40b3-bac6-4bad-b516-29bdf719f8a3 # Text: Source Url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bd2dbbb3-d9c6-4c35-a311-7c22a5d3f63d
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 17490b94-d86a-40c5-bc48-932d8c81319f
        userCondition: null
fs: images
handle: images
name: Images
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: transforms
transformSubpath: craft-transforms/images
