fieldLayouts:
  38d718c0-a8fd-4a1e-8136-9daf72525bd7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 5564ba9c-342c-4e49-9683-d969feeeb42a
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 55a8f195-17f6-41b9-983f-06bb0d4b973e # Text: Title Overwrite
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 94114dda-d0c2-4e16-8210-457baccdd17a
            userCondition: null
            warning: null
            width: 50
          -
            attribute: alt
            class: null
            cols: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 075f5d0e-9a65-41f1-8c51-7ed3adf3af4a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: aac37142-e533-49aa-8665-b8cc6360e98b # Text: Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4e12b584-9c3e-4c85-8577-6ca6ca65f5f6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 86a0304b-60f0-4f7a-9b45-de3c05eec04b # Text: Source
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6916b715-9612-4744-bc4b-ccc42ac3c627
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: bc1e40b3-bac6-4bad-b516-29bdf719f8a3 # Text: Source Url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 21480a14-55f2-43bd-b467-bc6e2c1e343d
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: a335ade1-e2fd-4066-8c0c-764bb223afa4
        userCondition: null
fs: templateImages
handle: templateImages
name: 'Template Images'
sortOrder: 3
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: transforms
transformSubpath: craft-transforms/templateImages
