fieldLayouts:
  1c050c97-46a7-44da-8b07-841009d282f4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 0d54794f-2cbf-4dce-9dd1-0375444002b9
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 55a8f195-17f6-41b9-983f-06bb0d4b973e # Text: Title Overwrite
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 97257e32-7e65-44ea-bb80-6c7818233e32
            userCondition: null
            warning: null
            width: 50
          -
            attribute: alt
            class: null
            cols: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 72092439-a6c2-4a17-a159-59712c76fb53
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: aac37142-e533-49aa-8665-b8cc6360e98b # Text: Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3cc5b53e-0cd2-49da-8c61-cc39d3cbb1c0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 86a0304b-60f0-4f7a-9b45-de3c05eec04b # Text: Source
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9bf401fe-b93e-4363-87f5-ed103d6daab7
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: bc1e40b3-bac6-4bad-b516-29bdf719f8a3 # Text: Source Url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cb63dc04-e308-43ba-9c45-916ed18fa52d
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 7fa2cead-3f59-4c5b-8562-8ee83d4acf7b
        userCondition: null
fs: users
handle: users
name: Users
sortOrder: 4
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: transforms
transformSubpath: craft-transforms/users
